In [1]:
import torch

x = torch.empty(1)
print(x)

tensor([1.8062e-35])


In [2]:
x = torch.empty(3)

In [3]:
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(1,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])


In [5]:
x = torch.empty(5,2,3)
print(x)

tensor([[[1.8432e-35, 9.8371e-43, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [6]:
x = torch.empty(5,3)
print(x)

tensor([[1.8620e-35, 9.8371e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [7]:
x = torch.rand(2,2)

In [8]:
print(x)

tensor([[0.3471, 0.2467],
        [0.6390, 0.1367]])


In [10]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [11]:
print(x.size())


torch.Size([2, 2])


In [12]:
x = torch.tensor([2.5, 0.1,3.5])

In [13]:
print(x)

tensor([2.5000, 0.1000, 3.5000])


In [14]:
x =torch.rand(2,2)

In [15]:
y=torch.rand(2,2)

In [18]:
print(x)
print(y)

tensor([[0.0717, 0.7916],
        [0.7451, 0.0971]])
tensor([[0.1435, 0.2573],
        [0.1982, 0.3816]])


In [20]:
z= x+y
print(z)

tensor([[0.2152, 1.0489],
        [0.9433, 0.4787]])


In [21]:
y.add_(x)
print(y)

tensor([[0.2152, 1.0489],
        [0.9433, 0.4787]])


In [22]:
z = x - y

In [23]:
print(z)

tensor([[-0.1435, -0.2573],
        [-0.1982, -0.3816]])
